#include <windows.h>
#define USE_STUBLESS_PROXY
#include <rpcndr.h>
#include <rpcproxy.h>
#include <stddef.h>

#ifdef _DEBUG
#include "thk_Win9X.h"
#endif // _DEBUG

BOOL _divineStubInfo(	const void* pStubBuffer,
						const IID* piid,
						const BYTE** ppProcFmtString,
						const WORD** ppFcnOffsets,
						DWORD* pcMethods,
						BOOL* pbDual )
{
	// WIN_64_CHECK
	CInterfaceStubVtbl* pStubVtbl = (CInterfaceStubVtbl*)((size_t)(*(void**)pStubBuffer) - offsetof( CInterfaceStubVtbl, Vtbl ));
	
	// pDispatchTable will either point to a table of stub routines,
	// or to NULL, which indicates fully-interpreted stubs.
	if ( pStubVtbl->header.pDispatchTable )
	{
		// there is one special case we watch for.
		// dual interfaces with explicit p/s DLLs will have a dispatch table
		// plus a few other distinct characteristics.
		BOOL bDual = FALSE;
		if ( pStubVtbl->header.DispatchTableCount >= 7 )
		{
			const WORD* it = pStubVtbl->header.pServerInfo->FmtStringOffset + 3;
			const WORD* const end = it + 4;
			bDual = TRUE;
			while ( ( it != end ) && bDual )
				if ( 0xFFFF != *it++ ) // first four offsets (IDispatch) will be -1
					bDual = FALSE;
			if ( bDual )
			{
				// first four entries in dispatch table should point to
				// rpcrt4.dll:NdrStubForwardingFunction
				// (the best I can do without looking at opcodes is to simply
				//  verify that all four fcn pointers point to the same offset
				//  in the jump table).
				void** it = (void**)pStubVtbl->header.pDispatchTable + 3;
				void* const FirstFcn = *it;
				void** const end = it + 4;
				while ( ( it != end ) && bDual )
					if ( FirstFcn != *it++ )
						bDual = FALSE;
			}
		}

		if ( bDual )
			*pbDual = TRUE;
		else
		{
#ifdef _DEBUG
			wchar_t sz[80];
			StringFromGUID2( piid, sz, sizeof sz / sizeof *sz );
			thk_OutputDebugStringW( sz );
			thk_OutputDebugStringW( L"\nERROR: Delegator cannot block calls to the above interface because its stub is not fully-interpreted.\nReturning E_NOINTERFACE to caller!\n" );
#endif // _DEBUG
			return FALSE;
		}
	}
	
	// make sure there's no local/call_as methods in this interface,
	// since we'll have no way to discover the correct stack size
	// if the signature of the local fcn differs from the call_as version.
	if ( pStubVtbl->header.pServerInfo->ThunkTable )
	{
#ifdef _DEBUG
		wchar_t sz[80];
		StringFromGUID2( piid, sz, sizeof sz / sizeof *sz );
		thk_OutputDebugStringW( sz );
		thk_OutputDebugStringW( L"\nERROR: Delegator cannot block calls to the above interface because at least one method within it uses the [call_as] IDL attribute.\nReturning E_NOINTERFACE to caller!\n" );
#endif // _DEBUG
		return FALSE;
	}

	// yet another sanity check, helps verify MIDL generated stubs
	if ( !IsEqualGUID( piid, pStubVtbl->header.piid ) )
	{
#ifdef _DEBUG
		wchar_t sz[80];
		StringFromGUID2( piid, sz, sizeof sz / sizeof *sz );
		thk_OutputDebugStringW( sz );
		thk_OutputDebugStringW( L"\nERROR: Delegator cannot block calls to the above interface because its stub does not appear to have been generated by MIDL.\nReturning E_NOINTERFACE to caller!\n" );
#endif // _DEBUG
		return FALSE;
	}

	*ppProcFmtString = pStubVtbl->header.pServerInfo->ProcString;
	*ppFcnOffsets    = pStubVtbl->header.pServerInfo->FmtStringOffset + 3;

	// get total number of methods, minus IUnknown
	*pcMethods = pStubVtbl->header.DispatchTableCount - 3;

	return TRUE;
}

BOOL _divineProxyInfo(	const void* pItf,
						const IID* piid,
						const BYTE** ppProcFmtString,
						const WORD** ppFcnOffsets )
{
	CInterfaceProxyHeader* pProxyHeader = (CInterfaceProxyHeader*)((BYTE*)(*(void**)pItf) - sizeof( CInterfaceProxyHeader ));
	const MIDL_STUBLESS_PROXY_INFO* pProxyInfo;

	// sanity check
	if ( !IsEqualGUID( pProxyHeader->piid, piid ) )
	{
#ifdef _DEBUG
		wchar_t sz[80];
		StringFromGUID2( piid, sz, sizeof sz / sizeof *sz );
		thk_OutputDebugStringW( sz );
		thk_OutputDebugStringW( L"\nERROR: Delegator cannot block calls to the above interface because its stub does not appear to have been generated by MIDL.\nReturning E_NOINTERFACE to caller!\n" );
#endif // _DEBUG
		return FALSE;
	}

	pProxyInfo = (MIDL_STUBLESS_PROXY_INFO*) pProxyHeader->pStublessProxyInfo;

	*ppProcFmtString = pProxyInfo->ProcFormatString;
	*ppFcnOffsets	 = pProxyInfo->FormatStringOffset;

	return TRUE;
}
